version: "3.8"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  workspace:
    build: ${APP_CODE_PATH_HOST}
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ${APP_CODE_PATH_HOST}/:/usr/src/app/
    ports:
      - "${WORKSPACE_PORT}:8000"
    networks:
      - backend

  redis:
    image: redis:8.0.3
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend




