apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-redis"
spec:
  serviceName: "{{ .Release.Name }}-redis"
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-redis"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-redis"
    spec:
      containers:
      - name: redis
        image: {{ $.Values.redis.image }}
        ports:
          - containerPort: {{ $.Values.redis.port }}
        volumeMounts:
          - name: redis-data
            mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $.Values.redis.storageSize }}

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-redis"
spec:
  selector:
    app: "{{ .Release.Name }}-redis"
  ports:
  - name: redis
    port: {{ $.Values.redis.port }}
